name: Build and Push Overwatch Docker Image

on:
  push:
    branches: ["**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: overwatch

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2

      - id: tags
        run: |
          IMG="ghcr.io/${{ github.repository_owner }}/zeitvertreib-overwatch"
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tags=$IMG:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=$IMG:${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - uses: docker/build-push-action@v4
        with:
          context: overwatch
          push: true
          tags: ${{ steps.tags.outputs.tags }}
